import FWCore.ParameterSet.Config as cms

pixelHitAnalyzer = cms.EDAnalyzer('PixelHitAnalyzer',
      vertexSrc = cms.vstring('pixelVertices'),
      trackSrc = cms.InputTag('pixel3ProtoTracks'),
      doMC = cms.untracked.bool(True),
      doTrackingParticle = cms.untracked.bool(True),
      hltTrgNames  = cms.untracked.vstring(
      'HLT_Activity_EcalREM',
      'HLT_Activity_L1A',
      'HLT_Activity_PixelClusters',
      'HLT_BackwardBSC',
      'HLT_CSCBeamHalo',
      'HLT_ForwardBSC',
      'HLT_FwdJet20U',
      'HLT_HFThreshold',
      'HLT_HighMultiplicityBSC',
      'HLT_L1SingleEG2',
      'HLT_L1SingleEG2_NoBPTX',
      'HLT_L1SingleEG5',
      'HLT_L1SingleForJet',
      'HLT_L1_BPTX',
      'HLT_L1_BPTX_MinusOnly',
      'HLT_L1_BPTX_PlusOnly',
      'HLT_L1_BSC',
      'HLT_L1_HFtech',
      'HLT_MinBias',
      'HLT_MinBiasBSC',
      'HLT_MinBiasBSC_OR',
      'HLT_MinBiasEcal',
      'HLT_MinBiasHcal',
      'HLT_MinBiasPixel_DoubleIsoTrack5',
      'HLT_MinBiasPixel_DoubleTrack',
      'HLT_MinBiasPixel_SingleTrack',
      'HLT_Mu3',
      'HLT_Random',
      'HLT_ZeroBias'
      ),

)
